### PR TITLE
Fix --hazelcast-version selection

### PR DESCRIPTION
**Pull request by Holmistr**

### CODE REVIEW

**Review by huseyinbabal — APPROVED** [review]

**Review by huseyinbabal — CHANGES_REQUESTED** [review]
https://github.com/hazelcast/hazelcast-cloud-sdk-go/blob/1af599ecae8cdca3f0db83bd71525d20bf463fd5/models/cluster.go we need to add 4.2 to golang sdk

**Comment by huseyinbabal** [comment]
I will handle go sdk part

**Comment by Holmistr** [comment]
Thanks :)

**Comment by huseyinbabal** [comment]
Closing in sake of https://github.com/hazelcast/hazelcast-cloud-cli/pull/30

**Pull request closed without merging**
